language: java
dist: bionic
group: travis_lts
git:
  depth: 9999999
  lfs_skip_smudge: true
jdk:
  - openjdk8
env:
  matrix:
  - SCALA_VERSION=2.11 TEST_TYPE=cloud UPLOAD=true TESTS_REQUIRE_GCLOUD=true
 global:
  #gradle needs this
  - TERM=dumb
  #limit gradle jvm memory and disable daemon
  - GRADLE_OPTS="-Xmx2048m -Dorg.gradle.daemon=false"
  #google cloud stuff
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - export GCLOUD_HOME=$HOME/gcloud/google-cloud-sdk/bin
  - export CLOUDSDK_PYTHON_SITEPACKAGES=1
  - export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/servicekey.json
  #hellbender specific variables
  - HELLBENDER_TEST_INPUTS=gs://hellbender/test/resources/
  - HELLBENDER_TEST_STAGING=gs://hellbender-test-logs/staging/
  - HELLBENDER_TEST_LOGS=/hellbender-test-logs/build_reports/
  - HELLBENDER_TEST_PROJECT=broad-dsde-dev
  - HELLBENDER_JSON_SERVICE_ACCOUNT_KEY=servicekey.json
  #Work around for https://github.com/googleapis/google-cloud-java/issues/5884
  - export GOOGLE_CLOUD_PROJECT=$HELLBENDER_TEST_PROJECT
  # For cromwell jar download
  - export CROMWELL_JAR=$HOME/cromwell-51.jar
  - export WOMTOOL_JAR=$HOME/womtool-51.jar
before_install:
- pwd
- ls -lh .
- if [[ ${TRAVIS_SECURE_ENV_VARS} == true ]]; then
    if [[ ${TESTS_REQUIRE_GCLOUD} == true ]]; then
      scripts/travis/install_and_authenticate_to_gcloud.sh;
    fi;
  fi;
