codecov:
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null
        informational: true

    patch:
      default:
        target: auto
        branches: null
        informational: true

    changes:
      default:
        branches: null
        informational: true


comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
  wait_for_ci: true # wait for the entire github actions test suite to finish before posting the coverage comment
